# Generated by Django 2.2 on 2019-04-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=25)),
                ('dept_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('employee_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('leaves_this_year', models.IntegerField()),
                ('leaves_next_year', models.IntegerField()),
                ('password', models.CharField(default='abcdefgh', max_length=50)),
                ('employee_email', models.CharField(default='', max_length=100)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.department')),
            ],
        ),
        migrations.CreateModel(
            name='hiring_request',
            fields=[
                ('request_id', models.IntegerField(primary_key=True, serialize=False)),
                ('associate_name', models.CharField(max_length=30)),
                ('associate_type', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=15)),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='leave_request_final',
            fields=[
                ('request_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('faculty_role', models.CharField(max_length=30)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.employees')),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='project_budget',
            fields=[
                ('project_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee_portal.projects')),
                ('manpower_budget', models.IntegerField()),
                ('travel_budget', models.IntegerField()),
                ('equipment_budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tee_request',
            fields=[
                ('request_id', models.IntegerField(primary_key=True, serialize=False)),
                ('expenditure_type', models.CharField(max_length=30)),
                ('ammount', models.IntegerField()),
                ('status', models.CharField(max_length=15)),
                ('comments', models.CharField(max_length=500)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.projects')),
            ],
        ),
        migrations.CreateModel(
            name='leave_request_status',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('withAuth', models.CharField(max_length=25)),
                ('stage', models.IntegerField(default=1)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.type')),
            ],
        ),
        migrations.CreateModel(
            name='leave_request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField(default='')),
                ('endDate', models.DateTimeField(default='')),
                ('reason', models.CharField(max_length=500)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.employees')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.leave_request_status')),
            ],
        ),
        migrations.CreateModel(
            name='expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_type', models.CharField(max_length=30)),
                ('expenditure', models.IntegerField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.projects')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.roles'),
        ),
        migrations.AddField(
            model_name='employees',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.type'),
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=500)),
                ('approvalStatus', models.CharField(max_length=500)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.employees')),
                ('request_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee_portal.leave_request')),
            ],
        ),
        migrations.CreateModel(
            name='project_associate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.employees')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.projects')),
            ],
            options={
                'unique_together': {('project_id', 'employee_id')},
            },
        ),
        migrations.CreateModel(
            name='department_roles',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee_portal.employees')),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.department')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.roles')),
            ],
        ),
        migrations.CreateModel(
            name='cfti_matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.roles')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.type')),
            ],
            options={
                'unique_together': {('type', 'years_of_experience')},
            },
        ),
        migrations.CreateModel(
            name='bonus_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=25)),
                ('bonus', models.DecimalField(decimal_places=3, max_digits=5)),
                ('status', models.CharField(max_length=10)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.roles')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.type')),
            ],
            options={
                'unique_together': {('role_id', 'month_year')},
            },
        ),
    ]
