# Generated by Django 2.2 on 2019-04-26 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='request_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee_portal.leave_request'),
        ),
        migrations.AddField(
            model_name='status',
            name='stage',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leave_request',
            name='request_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
