# Generated by Django 2.2 on 2019-04-25 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='type',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='bonus_request',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.type'),
        ),
        migrations.AlterField(
            model_name='cfti_matrix',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.type'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.type'),
        ),
    ]
