# Generated by Django 2.2 on 2019-04-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0002_pay_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_slip',
            name='bonus',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
