# Generated by Django 2.2 on 2019-04-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0002_auto_20190426_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.status'),
        ),
    ]
