# Generated by Django 2.2 on 2019-04-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0003_auto_20190426_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus_request',
            name='bonus',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pay_slip',
            name='bonus',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pay_slip',
            name='total',
            field=models.IntegerField(),
        ),
    ]
