# Generated by Django 2.2 on 2019-04-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0004_auto_20190426_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='regSpecial',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(default='jnvktmdak003', max_length=20)),
            ],
        ),
    ]
