# Generated by Django 2.2 on 2019-04-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0004_auto_20190426_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_request',
            name='approvalStatus',
            field=models.CharField(default='Pending', max_length=500),
            preserve_default=False,
        ),
    ]
