# Generated by Django 2.2 on 2019-04-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0005_regspecial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='regSpecial',
            new_name='reg_special',
        ),
    ]
