# Generated by Django 2.2 on 2019-04-26 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0006_auto_20190426_1920'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pay_slip',
            unique_together=set(),
        ),
    ]
